"""Fake adapter for deterministic orchestration tests."""

from __future__ import annotations

import json
from pathlib import Path

from ..models import (
    ChangeProposal,
    ReviewFinding,
    TaskAssignment,
    WorkerPromptEnvelope,
    WorkerResult,
    WorkerStatus,
)
from .base import AgentAdapter


class FakeAgentAdapter(AgentAdapter):
    name = "fake"

    async def run_assignment(self, assignment: TaskAssignment, envelope: WorkerPromptEnvelope, cwd: Path) -> WorkerResult:
        task = assignment.task
        scenario = task.metadata.get("fake_behavior", "success")
        files_read = task.read_paths or ["README.md"]
        files_changed = task.owned_paths if task.write_enabled else []
        if assignment.worktree_path and files_changed:
            for relative in files_changed:
                target = Path(assignment.worktree_path) / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(
                    f"# generated by fake agent\nrole = {task.role}\ntask = {task.task_id}\n",
                    encoding="utf-8",
                )
        if scenario == "timeout":
            raise TimeoutError(f"Fake timeout for task {task.task_id}")
        if scenario == "fail":
            return WorkerResult(
                task_id=task.task_id,
                agent_id=assignment.agent_id,
                role=task.role,
                status=WorkerStatus.failed,
                summary="Simulated failure",
                files_read=files_read,
                blockers=["simulated_failure"],
                confidence=0.2,
            )
        findings: list[ReviewFinding] = []
        if "review" in task.role:
            findings.append(
                ReviewFinding(
                    finding_id=f"{task.task_id}-finding",
                    title="Potential issue detected",
                    severity="medium",
                    category="risk",
                    description=f"{task.role} found a possible issue in {task.description}",
                    evidence=[json.dumps({"task": task.task_id, "role": task.role})],
                    confidence=0.6,
                    source_agent_id=assignment.agent_id,
                )
            )
        reply_payload = {
            "task_id": task.task_id,
            "agent_id": assignment.agent_id,
            "role": task.role,
            "status": WorkerStatus.succeeded.value,
            "summary": f"Completed {task.title}",
            "files_changed": files_changed,
            "findings": [item.model_dump(mode="json") for item in findings],
        }
        return WorkerResult(
            task_id=task.task_id,
            agent_id=assignment.agent_id,
            role=task.role,
            status=WorkerStatus.succeeded,
            summary=f"Completed {task.title}",
            assumptions=["Fake adapter used"],
            files_read=files_read,
            files_changed=files_changed,
            commands_run=["fake-agent run"],
            tests_run=["fake-test"] if task.role == "tester" else [],
            findings=findings,
            risks=task.metadata.get("risks", []),
            blockers=[],
            confidence=float(task.metadata.get("confidence", 0.8)),
            suggested_next_steps=["continue pipeline"],
            artifact_paths=[],
            branch_name=assignment.branch_name,
            worktree_path=assignment.worktree_path,
            change_proposal=ChangeProposal(
                summary=f"Applied fake changes for {task.task_id}",
                files_changed=files_changed,
                patch_summary=[f"updated {path}" for path in files_changed],
            ) if files_changed else None,
            metadata={
                "trace": {
                    "adapter": self.name,
                    "cwd": str(cwd),
                    "command": ["fake-agent", "run"],
                    "input_envelope": envelope.model_dump(mode="json"),
                    "reply": reply_payload,
                    "stdout": json.dumps(reply_payload, ensure_ascii=False),
                    "stderr": "",
                    "events": [
                        {"type": "input.received", "task_id": task.task_id, "role": task.role},
                        {"type": "reply.generated", "summary": f"Completed {task.title}"},
                    ],
                }
            },
        )
